# Generated by Django 5.2.17 on 2026-09-17 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_app_setting_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_tools', models.JSONField(blank=True, default=list, verbose_name='allowed tools')),
                ('require_disclosure', models.BooleanField(default=False, verbose_name='require disclosure')),
                ('require_human_approval', models.BooleanField(default=False, verbose_name='require human approval')),
                ('min_human_approvals', models.PositiveIntegerField(default=1, verbose_name='minimum human approvals')),
                ('require_tests_for_ai_prs', models.BooleanField(default=False, verbose_name='require tests for AI PRs')),
                ('ai_pr_max_effective_lines', models.PositiveIntegerField(blank=True, null=True, verbose_name='maximum effective lines for an AI PR')),
                ('effective_from', models.DateTimeField(verbose_name='effective from')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'AI policy',
                'verbose_name_plural': 'AI policies',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='SensitivePathRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glob', models.CharField(max_length=400, verbose_name='path glob')),
                ('ai_mode', models.CharField(choices=[('forbidden', 'Forbidden'), ('needs_extra_review', 'Needs extra review')], max_length=30, verbose_name='AI mode')),
                ('description', models.CharField(blank=True, max_length=400, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('project', models.ForeignKey(blank=True, help_text='Empty means the rule applies globally.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensitive_path_rules', to='catalog.project', verbose_name='project')),
            ],
            options={
                'verbose_name': 'sensitive path rule',
                'verbose_name_plural': 'sensitive path rules',
                'indexes': [models.Index(fields=['project', 'is_active'], name='policy_sens_project_2ad8a6_idx')],
            },
        ),
    ]
