# Generated by Django 5.2.17 on 2026-09-17 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
        ('policy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_code', models.CharField(choices=[('DISCLOSURE_MISSING', 'Disclosure missing'), ('DISCLOSURE_MISMATCH', 'Disclosure mismatch'), ('TOOL_NOT_ALLOWED', 'Tool not allowed'), ('SENSITIVE_PATH_FORBIDDEN', 'Sensitive path forbidden'), ('SENSITIVE_PATH_REVIEW', 'Sensitive path needs review'), ('NO_HUMAN_APPROVAL', 'No human approval'), ('SELF_MERGE', 'Self-merge'), ('NO_TESTS', 'No tests'), ('AI_PR_TOO_LARGE', 'AI PR too large')], max_length=30, verbose_name='rule code')),
                ('severity', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10, verbose_name='severity')),
                ('details_params', models.JSONField(blank=True, default=dict, verbose_name='details params')),
                ('details_hash', models.CharField(max_length=64, verbose_name='details hash')),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('waived', 'Waived'), ('resolved', 'Resolved')], default='open', max_length=20, verbose_name='status')),
                ('resolution_comment', models.TextField(blank=True, verbose_name='resolution comment')),
                ('resolved_automatically', models.BooleanField(default=False, verbose_name='resolved automatically')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('pull_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='activity.pullrequest', verbose_name='pull request')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_violations', to=settings.AUTH_USER_MODEL, verbose_name='resolved by')),
            ],
            options={
                'verbose_name': 'policy violation',
                'verbose_name_plural': 'policy violations',
                'indexes': [models.Index(fields=['status', 'severity'], name='policy_poli_status_5d66ec_idx'), models.Index(fields=['rule_code', 'created_at'], name='policy_poli_rule_co_530155_idx')],
                'constraints': [models.UniqueConstraint(fields=('pull_request', 'rule_code', 'details_hash'), name='uniq_violation_pr_rule_hash')],
            },
        ),
    ]
