# Generated by Django 5.2.17 on 2026-09-17 19:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_commit_author_email_identity'),
        ('catalog', '0005_policy_settings'),
        ('policy', '0002_policyviolation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensitivepathrule',
            options={'ordering': ['project_id', 'glob'], 'verbose_name': 'sensitive path rule', 'verbose_name_plural': 'sensitive path rules'},
        ),
        migrations.AlterField(
            model_name='aipolicy',
            name='effective_from',
            field=models.DateTimeField(unique=True, verbose_name='effective from'),
        ),
        migrations.AddIndex(
            model_name='policyviolation',
            index=models.Index(fields=['pull_request', 'status'], name='policy_poli_pull_re_dacd5d_idx'),
        ),
        migrations.AddConstraint(
            model_name='sensitivepathrule',
            constraint=models.UniqueConstraint(fields=('project', 'glob'), name='uniq_sensitive_path_project_glob'),
        ),
        migrations.AddConstraint(
            model_name='sensitivepathrule',
            constraint=models.UniqueConstraint(condition=models.Q(('project__isnull', True)), fields=('glob',), name='uniq_sensitive_path_global_glob'),
        ),
    ]
