# Phase 12, stage 7 — the PLANEKS AI Engineering Standards as checks: fifteen new rule codes, the
# AIPolicy toggles that gate them (every one off, so an upgrade raises nothing until a lead turns
# something on), SensitivePathRule.risk_level and its advisory mode.

# Generated by Django 5.2.17 on 2026-09-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_diff_analysis_repositories_setting'),
        ('policy', '0003_policy_engine'),
    ]

    operations = [
        migrations.AddField(
            model_name='aipolicy',
            name='ai_reviewer_identities',
            field=models.JSONField(blank=True, default=list, help_text='GitHub logins of the AI reviewers a pull request is expected to have run.', verbose_name='AI reviewer logins'),
        ),
        migrations.AddField(
            model_name='aipolicy',
            name='designated_reviewers',
            field=models.ManyToManyField(blank=True, help_text="People whose approval satisfies a migration's extra-review requirement.", related_name='designated_for_policies', to='catalog.person', verbose_name='designated reviewers'),
        ),
        migrations.AddField(
            model_name='aipolicy',
            name='flag_agent_config_changes',
            field=models.BooleanField(default=False, verbose_name='flag agent configuration changes'),
        ),
        migrations.AddField(
            model_name='aipolicy',
            name='flag_new_dependencies_in_ai_prs',
            field=models.BooleanField(default=False, verbose_name='flag new dependencies in AI PRs'),
        ),
        migrations.AddField(
            model_name='aipolicy',
            name='forbid_ai_only_approval',
            field=models.BooleanField(default=False, verbose_name='forbid AI-only approval'),
        ),
        migrations.AddField(
            model_name='aipolicy',
            name='forbid_ci_bypass',
            field=models.BooleanField(default=False, verbose_name='forbid bypassing the quality gate'),
        ),
        migrations.AddField(
            model_name='aipolicy',
            name='forbid_rubber_stamp_approval',
            field=models.BooleanField(default=False, verbose_name='forbid rubber-stamp approval of AI PRs'),
        ),
        migrations.AddField(
            model_name='aipolicy',
            name='forbid_scope_creep',
            field=models.BooleanField(default=False, verbose_name='forbid scope creep in AI PRs'),
        ),
        migrations.AddField(
            model_name='aipolicy',
            name='forbid_secret_artifacts',
            field=models.BooleanField(default=False, verbose_name='forbid committing credential files'),
        ),
        migrations.AddField(
            model_name='aipolicy',
            name='forbid_test_weakening',
            field=models.BooleanField(default=False, verbose_name='forbid weakening tests'),
        ),
        migrations.AddField(
            model_name='aipolicy',
            name='high_risk_min_approvals',
            field=models.PositiveIntegerField(default=2, verbose_name='minimum approvals for high risk'),
        ),
        migrations.AddField(
            model_name='aipolicy',
            name='max_effective_lines_by_risk',
            field=models.JSONField(blank=True, default=dict, verbose_name='maximum effective lines by risk level'),
        ),
        migrations.AddField(
            model_name='aipolicy',
            name='require_ai_comments_resolved',
            field=models.BooleanField(default=False, verbose_name='require AI review comments to be resolved'),
        ),
        migrations.AddField(
            model_name='aipolicy',
            name='require_ai_review_first',
            field=models.BooleanField(default=False, verbose_name='require an AI review'),
        ),
        migrations.AddField(
            model_name='aipolicy',
            name='require_high_risk_plan',
            field=models.BooleanField(default=False, verbose_name='require a plan for high-risk changes'),
        ),
        migrations.AddField(
            model_name='aipolicy',
            name='require_risk_level',
            field=models.BooleanField(default=False, verbose_name='require a stated risk level'),
        ),
        migrations.AddField(
            model_name='aipolicy',
            name='require_task_link',
            field=models.BooleanField(default=False, verbose_name='require a linked task'),
        ),
        migrations.AddField(
            model_name='aipolicy',
            name='require_verification_note',
            field=models.BooleanField(default=False, verbose_name='require a verification note'),
        ),
        migrations.AddField(
            model_name='sensitivepathrule',
            name='risk_level',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10, verbose_name='risk level'),
        ),
        migrations.AlterField(
            model_name='policyviolation',
            name='rule_code',
            field=models.CharField(choices=[('DISCLOSURE_MISSING', 'Disclosure missing'), ('DISCLOSURE_MISMATCH', 'Disclosure mismatch'), ('TOOL_NOT_ALLOWED', 'Tool not allowed'), ('SENSITIVE_PATH_FORBIDDEN', 'Sensitive path forbidden'), ('SENSITIVE_PATH_REVIEW', 'Sensitive path needs review'), ('NO_HUMAN_APPROVAL', 'No human approval'), ('SELF_MERGE', 'Self-merge'), ('NO_TESTS', 'No tests'), ('AI_PR_TOO_LARGE', 'AI PR too large'), ('QUALITY_GATE_BYPASSED', 'Quality gate bypassed'), ('TEST_WEAKENED', 'Tests weakened'), ('AI_ONLY_APPROVAL', 'Approved only by AI'), ('AI_REVIEW_MISSING', 'AI review missing'), ('AI_REVIEW_UNRESOLVED', 'AI review comments unresolved'), ('HIGH_RISK_NO_PLAN', 'High-risk change with no plan'), ('RISK_LEVEL_MISSING', 'Risk level not stated'), ('VERIFICATION_MISSING', 'Verification not stated'), ('TASK_LINK_MISSING', 'Task not linked'), ('NEW_DEPENDENCY_AI', 'New dependency in an AI PR'), ('MIGRATION_AI_INSUFFICIENT_REVIEW', 'Migration in an AI PR without designated review'), ('SECRET_ARTIFACT_COMMITTED', 'Credential file committed'), ('AGENT_CONFIG_CHANGED', 'Agent configuration changed'), ('SCOPE_CREEP', 'Scope creep'), ('RUBBER_STAMP_ON_AI_PR', 'Rubber-stamp approval of an AI PR')], max_length=40, verbose_name='rule code'),
        ),
        migrations.AlterField(
            model_name='sensitivepathrule',
            name='ai_mode',
            field=models.CharField(choices=[('forbidden', 'Forbidden'), ('needs_extra_review', 'Needs extra review'), ('advisory', 'Advisory (risk level only)')], max_length=30, verbose_name='AI mode'),
        ),
    ]
