# Generated by Django 5.2.17 on 2026-09-17 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRollup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('scope_type', models.CharField(choices=[('global', 'Global'), ('project', 'Project'), ('repo', 'Repository'), ('person', 'Person')], max_length=10, verbose_name='scope type')),
                ('scope_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='scope id')),
                ('cohort', models.CharField(choices=[('all', 'All'), ('ai', 'AI'), ('non_ai', 'Non-AI')], max_length=10, verbose_name='cohort')),
                ('metric_key', models.CharField(max_length=100, verbose_name='metric key')),
                ('value', models.FloatField(blank=True, null=True, verbose_name='value')),
                ('sample_size', models.PositiveIntegerField(default=0, verbose_name='sample size')),
                ('computed_at', models.DateTimeField(auto_now=True, verbose_name='computed at')),
            ],
            options={
                'verbose_name': 'daily rollup',
                'verbose_name_plural': 'daily rollups',
                'indexes': [models.Index(fields=['metric_key', 'date'], name='metrics_dai_metric__1774b8_idx'), models.Index(fields=['scope_type', 'scope_id', 'date'], name='metrics_dai_scope_t_c6b353_idx')],
                'constraints': [models.UniqueConstraint(fields=('date', 'scope_type', 'scope_id', 'cohort', 'metric_key'), name='uniq_dailyrollup_scoped'), models.UniqueConstraint(condition=models.Q(('scope_id__isnull', True)), fields=('date', 'scope_type', 'cohort', 'metric_key'), name='uniq_dailyrollup_global')],
            },
        ),
    ]
