# Generated by Django 5.2.17 on 2026-09-17 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='version')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'data version',
                'verbose_name_plural': 'data version',
            },
        ),
        migrations.CreateModel(
            name='DirtyDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='date')),
                ('marked_at', models.DateTimeField(auto_now_add=True, verbose_name='marked at')),
            ],
            options={
                'verbose_name': 'dirty day',
                'verbose_name_plural': 'dirty days',
            },
        ),
    ]
