# Generated by Django 5.2.17 on 2026-09-17 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_app_setting_defaults'),
        ('policy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha', models.CharField(max_length=64, verbose_name='sha')),
                ('github_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='GitHub node id')),
                ('authored_at', models.DateTimeField(blank=True, null=True, verbose_name='authored at')),
                ('committed_at', models.DateTimeField(blank=True, null=True, verbose_name='committed at')),
                ('message', models.TextField(blank=True, verbose_name='message')),
                ('additions', models.PositiveIntegerField(blank=True, null=True, verbose_name='additions')),
                ('deletions', models.PositiveIntegerField(blank=True, null=True, verbose_name='deletions')),
                ('co_authors', models.JSONField(blank=True, default=list, verbose_name='co-authors')),
                ('trailers', models.JSONField(blank=True, default=dict, verbose_name='trailers')),
                ('raw', models.JSONField(blank=True, null=True, verbose_name='raw payload')),
                ('author_identity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_commits', to='catalog.identity', verbose_name='author identity')),
                ('committer_identity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committed_commits', to='catalog.identity', verbose_name='committer identity')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='catalog.repository', verbose_name='repository')),
            ],
            options={
                'verbose_name': 'commit',
                'verbose_name_plural': 'commits',
            },
        ),
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='number')),
                ('github_id', models.CharField(max_length=100, unique=True, verbose_name='GitHub node id')),
                ('title', models.CharField(blank=True, max_length=500, verbose_name='title')),
                ('body', models.TextField(blank=True, verbose_name='body')),
                ('state', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('merged', 'Merged')], max_length=10, verbose_name='state')),
                ('is_draft', models.BooleanField(default=False, verbose_name='is draft')),
                ('base_ref', models.CharField(blank=True, max_length=200, verbose_name='base ref')),
                ('head_ref', models.CharField(blank=True, max_length=200, verbose_name='head ref')),
                ('created_at', models.DateTimeField(verbose_name='created at')),
                ('ready_for_review_at', models.DateTimeField(blank=True, null=True, verbose_name='ready for review at')),
                ('first_commit_at', models.DateTimeField(blank=True, null=True, verbose_name='first commit at')),
                ('first_review_at', models.DateTimeField(blank=True, null=True, verbose_name='first review at')),
                ('first_approval_at', models.DateTimeField(blank=True, null=True, verbose_name='first approval at')),
                ('merged_at', models.DateTimeField(blank=True, null=True, verbose_name='merged at')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='closed at')),
                ('last_activity_at', models.DateTimeField(blank=True, null=True, verbose_name='last activity at')),
                ('updated_at_github', models.DateTimeField(blank=True, null=True, verbose_name='updated at (GitHub)')),
                ('merge_commit_sha', models.CharField(blank=True, max_length=64, verbose_name='merge commit sha')),
                ('merge_method', models.CharField(choices=[('merge', 'Merge'), ('squash', 'Squash'), ('rebase', 'Rebase'), ('unknown', 'Unknown')], default='unknown', max_length=10, verbose_name='merge method')),
                ('additions', models.PositiveIntegerField(blank=True, null=True, verbose_name='additions')),
                ('deletions', models.PositiveIntegerField(blank=True, null=True, verbose_name='deletions')),
                ('changed_files', models.PositiveIntegerField(blank=True, null=True, verbose_name='changed files')),
                ('effective_additions', models.PositiveIntegerField(blank=True, null=True, verbose_name='effective additions')),
                ('effective_deletions', models.PositiveIntegerField(blank=True, null=True, verbose_name='effective deletions')),
                ('labels', models.JSONField(blank=True, default=list, verbose_name='labels')),
                ('review_rounds', models.PositiveIntegerField(blank=True, null=True, verbose_name='review rounds')),
                ('commits_after_first_review', models.PositiveIntegerField(blank=True, null=True, verbose_name='commits after first review')),
                ('raw', models.JSONField(blank=True, null=True, verbose_name='raw payload')),
                ('size_bucket', models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=2, null=True, verbose_name='size bucket')),
                ('is_revert', models.BooleanField(default=False, verbose_name='is revert')),
                ('is_hotfix', models.BooleanField(default=False, verbose_name='is hotfix')),
                ('has_test_changes', models.BooleanField(default=False, verbose_name='has test changes')),
                ('ai_status', models.CharField(choices=[('ai_explicit', 'AI explicit'), ('ai_disclosed', 'AI disclosed'), ('ai_suspected', 'AI suspected'), ('no_ai', 'No AI'), ('unknown', 'Unknown')], default='unknown', max_length=20, verbose_name='AI status')),
                ('ai_tools', models.JSONField(blank=True, default=list, verbose_name='AI tools')),
                ('ai_disclosure', models.CharField(choices=[('none', 'None'), ('partial', 'Partial'), ('substantial', 'Substantial'), ('missing', 'Missing'), ('ambiguous', 'Ambiguous')], default='missing', max_length=20, verbose_name='AI disclosure')),
                ('is_rubber_stamp', models.BooleanField(default=False, verbose_name='is rubber stamp')),
                ('is_self_merged', models.BooleanField(default=False, verbose_name='is self-merged')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_pull_requests', to='catalog.identity', verbose_name='author')),
                ('merged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_pull_requests', to='catalog.identity', verbose_name='merged by')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pull_requests', to='catalog.repository', verbose_name='repository')),
                ('reverts_pr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reverted_by', to='activity.pullrequest', verbose_name='reverts PR')),
            ],
            options={
                'verbose_name': 'pull request',
                'verbose_name_plural': 'pull requests',
            },
        ),
        migrations.CreateModel(
            name='PRFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=1000, verbose_name='path')),
                ('status', models.CharField(blank=True, max_length=20, verbose_name='status')),
                ('additions', models.PositiveIntegerField(blank=True, null=True, verbose_name='additions')),
                ('deletions', models.PositiveIntegerField(blank=True, null=True, verbose_name='deletions')),
                ('is_test', models.BooleanField(default=False, verbose_name='is test')),
                ('is_excluded', models.BooleanField(default=False, verbose_name='is excluded')),
                ('matched_sensitive_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_files', to='policy.sensitivepathrule', verbose_name='matched sensitive rule')),
                ('pull_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='activity.pullrequest', verbose_name='pull request')),
            ],
            options={
                'verbose_name': 'PR file',
                'verbose_name_plural': 'PR files',
            },
        ),
        migrations.CreateModel(
            name='CheckStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_sha', models.CharField(max_length=64, verbose_name='commit sha')),
                ('is_first_ci_commit', models.BooleanField(default=False, verbose_name='is first CI commit')),
                ('rollup_state', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('ERROR', 'Error'), ('PENDING', 'Pending'), ('NONE', 'None')], max_length=10, verbose_name='rollup state')),
                ('observed_at', models.DateTimeField(blank=True, null=True, verbose_name='observed at')),
                ('pull_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_statuses', to='activity.pullrequest', verbose_name='pull request')),
            ],
            options={
                'verbose_name': 'check status',
                'verbose_name_plural': 'check statuses',
            },
        ),
        migrations.CreateModel(
            name='PullRequestCommit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(verbose_name='position')),
                ('commit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pull_request_commits', to='activity.commit', verbose_name='commit')),
                ('pull_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pull_request_commits', to='activity.pullrequest', verbose_name='pull request')),
            ],
            options={
                'verbose_name': 'pull request commit',
                'verbose_name_plural': 'pull request commits',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('APPROVED', 'Approved'), ('CHANGES_REQUESTED', 'Changes requested'), ('COMMENTED', 'Commented'), ('DISMISSED', 'Dismissed')], max_length=20, verbose_name='state')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='submitted at')),
                ('body_length', models.PositiveIntegerField(blank=True, null=True, verbose_name='body length')),
                ('comments_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='comments count')),
                ('github_id', models.CharField(max_length=100, unique=True, verbose_name='GitHub node id')),
                ('raw', models.JSONField(blank=True, null=True, verbose_name='raw payload')),
                ('pull_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='activity.pullrequest', verbose_name='pull request')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='catalog.identity', verbose_name='reviewer')),
            ],
            options={
                'verbose_name': 'review',
                'verbose_name_plural': 'reviews',
            },
        ),
        migrations.CreateModel(
            name='ReviewComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='created at')),
                ('is_review_thread', models.BooleanField(default=False, verbose_name='is review thread')),
                ('body_length', models.PositiveIntegerField(blank=True, null=True, verbose_name='body length')),
                ('github_id', models.CharField(max_length=100, unique=True, verbose_name='GitHub node id')),
                ('raw', models.JSONField(blank=True, null=True, verbose_name='raw payload')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_comments', to='catalog.identity', verbose_name='author')),
                ('pull_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_comments', to='activity.pullrequest', verbose_name='pull request')),
            ],
            options={
                'verbose_name': 'review comment',
                'verbose_name_plural': 'review comments',
            },
        ),
        migrations.AddIndex(
            model_name='commit',
            index=models.Index(fields=['repository', 'committed_at'], name='activity_co_reposit_b01959_idx'),
        ),
        migrations.AddConstraint(
            model_name='commit',
            constraint=models.UniqueConstraint(fields=('repository', 'sha'), name='uniq_commit_repository_sha'),
        ),
        migrations.AddIndex(
            model_name='pullrequest',
            index=models.Index(fields=['repository', 'merged_at'], name='activity_pu_reposit_d63f03_idx'),
        ),
        migrations.AddIndex(
            model_name='pullrequest',
            index=models.Index(fields=['author', 'merged_at'], name='activity_pu_author__42d6fc_idx'),
        ),
        migrations.AddIndex(
            model_name='pullrequest',
            index=models.Index(fields=['state', 'is_draft', 'last_activity_at'], name='activity_pu_state_46339c_idx'),
        ),
        migrations.AddIndex(
            model_name='pullrequest',
            index=models.Index(fields=['ai_status', 'merged_at'], name='activity_pu_ai_stat_5a4896_idx'),
        ),
        migrations.AddIndex(
            model_name='pullrequest',
            index=models.Index(fields=['created_at'], name='activity_pu_created_76d7c9_idx'),
        ),
        migrations.AddConstraint(
            model_name='pullrequest',
            constraint=models.UniqueConstraint(fields=('repository', 'number'), name='uniq_pull_request_repository_number'),
        ),
        migrations.AddIndex(
            model_name='prfile',
            index=models.Index(fields=['pull_request', 'is_excluded'], name='activity_pr_pull_re_b35b78_idx'),
        ),
        migrations.AddConstraint(
            model_name='prfile',
            constraint=models.UniqueConstraint(fields=('pull_request', 'path'), name='uniq_pr_file_pull_request_path'),
        ),
        migrations.AddIndex(
            model_name='checkstatus',
            index=models.Index(fields=['pull_request', 'is_first_ci_commit'], name='activity_ch_pull_re_f938a2_idx'),
        ),
        migrations.AddConstraint(
            model_name='checkstatus',
            constraint=models.UniqueConstraint(fields=('pull_request', 'commit_sha'), name='uniq_check_status_pr_commit_sha'),
        ),
        migrations.AddConstraint(
            model_name='pullrequestcommit',
            constraint=models.UniqueConstraint(fields=('pull_request', 'commit'), name='uniq_pr_commit_pull_request_commit'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['pull_request', 'submitted_at'], name='activity_re_pull_re_d275c2_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['reviewer', 'submitted_at'], name='activity_re_reviewe_bb1fd9_idx'),
        ),
    ]
