# Generated by Django 5.2.17 on 2026-09-17 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
        ('catalog', '0003_sync_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='author_email_identity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_commits_by_email', to='catalog.identity', verbose_name='author email identity'),
        ),
    ]
