# Generated by Django 5.2.17 on 2026-09-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_commit_author_email_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequest',
            name='has_followup_fix',
            field=models.BooleanField(default=False, verbose_name='has follow-up fix'),
        ),
    ]
