# Phase 12, stage 7 — `PullRequest.review_requested_at` and `ReviewComment.is_resolved`, both
# from GraphQL fields the sync now asks for. `is_resolved` is nullable because an older GitHub
# Enterprise Server does not return it, and "unknown" must not read as "unresolved".

# Generated by Django 5.2.17 on 2026-09-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_pullrequest_has_followup_fix'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequest',
            name='review_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='review requested at'),
        ),
        migrations.AddField(
            model_name='reviewcomment',
            name='is_resolved',
            field=models.BooleanField(blank=True, null=True, verbose_name='is resolved'),
        ),
    ]
