# Generated by Django 5.2.17 on 2026-09-17 06:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_app_setting_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='started at')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='finished at')),
                ('trigger', models.CharField(choices=[('cli', 'CLI'), ('ui', 'UI'), ('schedule', 'Schedule')], max_length=10, verbose_name='trigger')),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='running', max_length=10, verbose_name='status')),
                ('stats', models.JSONField(blank=True, default=dict, verbose_name='stats')),
                ('stats_by_connection', models.JSONField(blank=True, default=dict, verbose_name='stats by connection')),
                ('error_log', models.TextField(blank=True, verbose_name='error log')),
                ('repositories', models.ManyToManyField(blank=True, related_name='sync_runs', to='catalog.repository', verbose_name='repositories')),
            ],
            options={
                'verbose_name': 'sync run',
                'verbose_name_plural': 'sync runs',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['started_at'], name='github_sync_started_96227f_idx')],
            },
        ),
    ]
