# Generated by Django 5.2.17 on 2026-09-17 08:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_sync', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('acquired_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='acquired at')),
                ('sync_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locks', to='github_sync.syncrun', verbose_name='sync run')),
            ],
            options={
                'verbose_name': 'sync lock',
                'verbose_name_plural': 'sync locks',
            },
        ),
    ]
