# Generated by Django 5.2.17 on 2026-09-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_sync', '0002_synclock'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncrun',
            name='since',
            field=models.DateTimeField(blank=True, help_text='The watermark override this run used, if any (a backfill sets it).', null=True, verbose_name='since'),
        ),
        migrations.AlterField(
            model_name='syncrun',
            name='trigger',
            field=models.CharField(choices=[('cli', 'CLI'), ('ui', 'UI'), ('schedule', 'Schedule'), ('backfill', 'Backfill')], max_length=10, verbose_name='trigger'),
        ),
    ]
