# Generated by Django 5.2.17 on 2026-09-17 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurnResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_days', models.PositiveIntegerField(verbose_name='window days')),
                ('lines_at_merge', models.PositiveIntegerField(blank=True, null=True, verbose_name='lines at merge')),
                ('lines_surviving', models.PositiveIntegerField(blank=True, null=True, verbose_name='lines surviving')),
                ('churn_ratio', models.FloatField(blank=True, null=True, verbose_name='churn ratio')),
                ('snapshot_sha', models.CharField(blank=True, max_length=64, verbose_name='snapshot sha')),
                ('computed_at', models.DateTimeField(auto_now=True, verbose_name='computed at')),
                ('status', models.CharField(choices=[('ok', 'OK'), ('unsupported_merge_method', 'Unsupported merge method'), ('too_large', 'Too large'), ('error', 'Error')], max_length=30, verbose_name='status')),
                ('error', models.TextField(blank=True, verbose_name='error')),
                ('pull_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='churn_results', to='activity.pullrequest', verbose_name='pull request')),
            ],
            options={
                'verbose_name': 'churn result',
                'verbose_name_plural': 'churn results',
                'indexes': [models.Index(fields=['status', 'computed_at'], name='churn_churn_status_8a05b3_idx')],
                'constraints': [models.UniqueConstraint(fields=('pull_request', 'window_days'), name='uniq_churn_pr_window')],
            },
        ),
    ]
