# Generated by Django 5.2.17 on 2026-09-17 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('detector', models.CharField(choices=[('commit_trailer', 'Commit trailer'), ('commit_author', 'Commit author'), ('pr_author', 'PR author'), ('pr_body_footer', 'PR body footer'), ('html_comment', 'HTML comment'), ('label', 'Label'), ('branch_pattern', 'Branch pattern'), ('commit_message', 'Commit message')], max_length=20, verbose_name='detector')),
                ('pattern', models.CharField(max_length=500, verbose_name='pattern')),
                ('tool', models.CharField(choices=[('claude_code', 'Claude Code'), ('copilot', 'Copilot'), ('cursor', 'Cursor'), ('codex', 'Codex'), ('devin', 'Devin'), ('gemini', 'Gemini'), ('aider', 'Aider'), ('windsurf', 'Windsurf'), ('chatgpt', 'ChatGPT'), ('other', 'Other')], max_length=20, verbose_name='tool')),
                ('confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10, verbose_name='confidence')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'detection rule',
                'verbose_name_plural': 'detection rules',
                'indexes': [models.Index(fields=['is_active', 'detector'], name='ai_detectio_is_acti_4617f6_idx')],
            },
        ),
        migrations.CreateModel(
            name='AISignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool', models.CharField(choices=[('claude_code', 'Claude Code'), ('copilot', 'Copilot'), ('cursor', 'Cursor'), ('codex', 'Codex'), ('devin', 'Devin'), ('gemini', 'Gemini'), ('aider', 'Aider'), ('windsurf', 'Windsurf'), ('chatgpt', 'ChatGPT'), ('other', 'Other')], max_length=20, verbose_name='tool')),
                ('confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10, verbose_name='confidence')),
                ('evidence', models.CharField(max_length=200, verbose_name='evidence')),
                ('detected_at', models.DateTimeField(auto_now_add=True, verbose_name='detected at')),
                ('commit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_signals', to='activity.commit', verbose_name='commit')),
                ('pull_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_signals', to='activity.pullrequest', verbose_name='pull request')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signals', to='ai_detection.detectionrule', verbose_name='rule')),
            ],
            options={
                'verbose_name': 'AI signal',
                'verbose_name_plural': 'AI signals',
                'indexes': [models.Index(fields=['pull_request', 'confidence'], name='ai_detectio_pull_re_8f615e_idx')],
            },
        ),
    ]
