# Generated by Django 5.2.17 on 2026-09-19 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_detection', '0002_evidence_hash_and_rule_name_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aisignal',
            name='tool',
            field=models.CharField(choices=[('claude_code', 'Claude Code'), ('copilot', 'Copilot'), ('cursor', 'Cursor'), ('codex', 'Codex'), ('devin', 'Devin'), ('gemini', 'Gemini'), ('aider', 'Aider'), ('windsurf', 'Windsurf'), ('chatgpt', 'ChatGPT'), ('charlie', 'Charlie'), ('other', 'Other')], max_length=20, verbose_name='tool'),
        ),
        migrations.AlterField(
            model_name='detectionrule',
            name='tool',
            field=models.CharField(choices=[('claude_code', 'Claude Code'), ('copilot', 'Copilot'), ('cursor', 'Cursor'), ('codex', 'Codex'), ('devin', 'Devin'), ('gemini', 'Gemini'), ('aider', 'Aider'), ('windsurf', 'Windsurf'), ('chatgpt', 'ChatGPT'), ('charlie', 'Charlie'), ('other', 'Other')], max_length=20, verbose_name='tool'),
        ),
    ]
