# Generated by Django 5.2.17 on 2026-09-20 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_detection', '0003_charlie_tool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionrule',
            name='detector',
            field=models.CharField(choices=[('commit_trailer', 'Commit trailer'), ('commit_author', 'Commit author'), ('pr_author', 'PR author'), ('pr_body_footer', 'PR body footer'), ('html_comment', 'HTML comment'), ('label', 'Label'), ('branch_pattern', 'Branch pattern'), ('commit_message', 'Commit message'), ('file_path', 'File path'), ('pr_title', 'PR title'), ('reviewer_identity', 'Reviewer identity'), ('merged_by_identity', 'Merged-by identity')], max_length=20, verbose_name='detector'),
        ),
    ]
