# Generated by Django 5.2.17 on 2026-09-20 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_pullrequest_has_followup_fix'),
        ('ai_detection', '0004_new_text_detectors'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='name')),
                ('kind', models.CharField(choices=[('fast_large_pr', 'Large change delivered very fast'), ('commit_burst', 'Burst of near-simultaneous substantial commits'), ('single_large_commit', 'Whole change in one large commit'), ('mass_file_creation', 'Many files created across many directories'), ('unused_new_dependency', 'New dependency nothing in the diff uses'), ('instant_review_response', 'Repeated commits moments after review comments')], max_length=40, verbose_name='kind')),
                ('params', models.JSONField(blank=True, default=dict, verbose_name='parameters')),
                ('tool', models.CharField(choices=[('claude_code', 'Claude Code'), ('copilot', 'Copilot'), ('cursor', 'Cursor'), ('codex', 'Codex'), ('devin', 'Devin'), ('gemini', 'Gemini'), ('aider', 'Aider'), ('windsurf', 'Windsurf'), ('chatgpt', 'ChatGPT'), ('charlie', 'Charlie'), ('other', 'Other')], default='other', max_length=20, verbose_name='tool')),
                ('confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10, verbose_name='confidence')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'structural signal rule',
                'verbose_name_plural': 'structural signal rules',
            },
        ),
        migrations.RemoveConstraint(
            model_name='aisignal',
            name='uniq_aisignal_pr_rule_evidence',
        ),
        migrations.AddField(
            model_name='aisignal',
            name='evidence_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='evidence code'),
        ),
        migrations.AddField(
            model_name='aisignal',
            name='evidence_params',
            field=models.JSONField(blank=True, default=dict, verbose_name='evidence parameters'),
        ),
        migrations.AlterField(
            model_name='aisignal',
            name='evidence',
            field=models.CharField(blank=True, max_length=200, verbose_name='evidence'),
        ),
        migrations.AlterField(
            model_name='aisignal',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signals', to='ai_detection.detectionrule', verbose_name='rule'),
        ),
        migrations.AddIndex(
            model_name='signalrule',
            index=models.Index(fields=['is_active', 'kind'], name='ai_detectio_is_acti_60a2de_idx'),
        ),
        migrations.AddConstraint(
            model_name='signalrule',
            constraint=models.CheckConstraint(condition=models.Q(('confidence', 'high'), _negated=True), name='signalrule_confidence_never_high'),
        ),
        migrations.AddField(
            model_name='aisignal',
            name='signal_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signals', to='ai_detection.signalrule', verbose_name='structural signal rule'),
        ),
        migrations.AddConstraint(
            model_name='aisignal',
            constraint=models.UniqueConstraint(condition=models.Q(('rule__isnull', False)), fields=('pull_request', 'rule', 'evidence_hash'), name='uniq_aisignal_pr_rule_evidence'),
        ),
        migrations.AddConstraint(
            model_name='aisignal',
            constraint=models.UniqueConstraint(condition=models.Q(('signal_rule__isnull', False)), fields=('pull_request', 'signal_rule', 'evidence_hash'), name='uniq_aisignal_pr_signal_rule_evidence'),
        ),
        migrations.AddConstraint(
            model_name='aisignal',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('rule__isnull', False), ('signal_rule__isnull', True)), models.Q(('rule__isnull', True), ('signal_rule__isnull', False)), _connector='OR'), name='aisignal_exactly_one_rule_family'),
        ),
    ]
