# Generated by Django 5.2.17 on 2026-09-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_detection', '0005_structural_signals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signalrule',
            name='kind',
            field=models.CharField(choices=[('fast_large_pr', 'Large change delivered very fast'), ('commit_burst', 'Burst of near-simultaneous substantial commits'), ('single_large_commit', 'Whole change in one large commit'), ('mass_file_creation', 'Many files created across many directories'), ('unused_new_dependency', 'New dependency nothing in the diff uses'), ('instant_review_response', 'Repeated commits moments after review comments'), ('throughput_shift', "Throughput jumped against the author's own history"), ('off_hours_volume', "Volume moved outside the author's usual hours"), ('test_ratio_lockstep', 'Test-to-code ratio barely varies across pull requests'), ('body_style_shift', "Pull-request descriptions broke from the author's own style")], max_length=40, verbose_name='kind'),
        ),
    ]
