# Phase 12, stage 6 — the diff signal family: three new kinds on `SignalRule`, and `DiffAnalysis`,
# one row per pull request recording what the churn clone's diff said. No data migration: the only
# kind whose family changed (`unused_new_dependency`) never produced a row, because it was
# registered silent until the diff pipeline existed.

# Generated by Django 5.2.17 on 2026-09-20 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_pullrequest_has_followup_fix'),
        ('ai_detection', '0006_baseline_signal_kinds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signalrule',
            name='kind',
            field=models.CharField(choices=[('fast_large_pr', 'Large change delivered very fast'), ('commit_burst', 'Burst of near-simultaneous substantial commits'), ('single_large_commit', 'Whole change in one large commit'), ('mass_file_creation', 'Many files created across many directories'), ('unused_new_dependency', 'New dependency nothing in the diff uses'), ('instant_review_response', 'Repeated commits moments after review comments'), ('throughput_shift', "Throughput jumped against the author's own history"), ('off_hours_volume', "Volume moved outside the author's usual hours"), ('test_ratio_lockstep', 'Test-to-code ratio barely varies across pull requests'), ('body_style_shift', "Pull-request descriptions broke from the author's own style"), ('wholesale_reformat', 'Large diff with almost no semantic change'), ('comment_density_outlier', 'Comment density far above the code it joins'), ('duplicated_blocks', 'The same block of code repeated across files')], max_length=40, verbose_name='kind'),
        ),
        migrations.CreateModel(
            name='DiffAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ok', 'OK'), ('no_clone', 'No clone available'), ('too_large', 'Too large'), ('unsupported_merge_method', 'Unsupported merge method'), ('error', 'Error')], max_length=30, verbose_name='status')),
                ('facts', models.JSONField(blank=True, default=dict, verbose_name='diff facts')),
                ('base_sha', models.CharField(blank=True, max_length=64, verbose_name='base sha')),
                ('head_sha', models.CharField(blank=True, max_length=64, verbose_name='head sha')),
                ('computed_at', models.DateTimeField(auto_now=True, verbose_name='computed at')),
                ('error', models.TextField(blank=True, verbose_name='error')),
                ('pull_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diff_analysis', to='activity.pullrequest', verbose_name='pull request')),
            ],
            options={
                'verbose_name': 'diff analysis',
                'verbose_name_plural': 'diff analyses',
                'indexes': [models.Index(fields=['status', 'computed_at'], name='ai_detectio_status_9be287_idx')],
            },
        ),
    ]
