# Generated by Django 5.2.17 on 2026-09-17 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='name')),
                ('kind', models.CharField(choices=[('fine_grained_pat', 'Fine-grained personal access token'), ('classic_pat', 'Classic personal access token'), ('github_app', 'GitHub App')], max_length=20, verbose_name='kind')),
                ('owner_login', models.CharField(blank=True, max_length=200, verbose_name='owner login')),
                ('token_encrypted', models.BinaryField(blank=True, null=True, verbose_name='encrypted token')),
                ('token_last4', models.CharField(blank=True, max_length=4, verbose_name='token last 4 characters')),
                ('token_login', models.CharField(blank=True, max_length=200, verbose_name='token login')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expires at')),
                ('status', models.CharField(choices=[('unverified', 'Unverified'), ('ok', 'OK'), ('degraded', 'Degraded'), ('invalid', 'Invalid'), ('expired', 'Expired')], default='unverified', max_length=20, verbose_name='status')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='last checked at')),
                ('last_check_result', models.JSONField(blank=True, default=dict, verbose_name='last check result')),
                ('rate_limit_remaining', models.IntegerField(blank=True, null=True, verbose_name='rate limit remaining')),
                ('rate_limit_reset_at', models.DateTimeField(blank=True, null=True, verbose_name='rate limit reset at')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('app_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='app id')),
                ('installation_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='installation id')),
                ('private_key_encrypted', models.BinaryField(blank=True, null=True, verbose_name='encrypted private key')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_connections', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'GitHub connection',
                'verbose_name_plural': 'GitHub connections',
            },
        ),
    ]
