# Generated by Django 5.2.17 on 2026-09-18 10:59

import apps.dashboards.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("table_csv", "Table (CSV)"),
                            ("table_xlsx", "Table (XLSX)"),
                            ("report_xlsx", "Report (XLSX)"),
                        ],
                        max_length=12,
                        verbose_name="kind",
                    ),
                ),
                ("params", models.JSONField(blank=True, default=dict, verbose_name="params")),
                ("language", models.CharField(default="en", max_length=8, verbose_name="language")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        storage=apps.dashboards.models.EXPORT_STORAGE,
                        upload_to="",
                        verbose_name="file",
                    ),
                ),
                ("rows", models.PositiveIntegerField(blank=True, null=True, verbose_name="rows")),
                ("error_code", models.CharField(blank=True, max_length=50, verbose_name="error code")),
                ("error_params", models.JSONField(blank=True, default=dict, verbose_name="error params")),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="created at"),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True, verbose_name="started at")),
                ("finished_at", models.DateTimeField(blank=True, null=True, verbose_name="finished at")),
                ("expires_at", models.DateTimeField(blank=True, null=True, verbose_name="expires at")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_jobs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "export job",
                "verbose_name_plural": "export jobs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "-created_at"], name="dashboards__user_id_525e2f_idx"),
                    models.Index(fields=["status"], name="dashboards__status_3aec57_idx"),
                ],
            },
        ),
    ]
