"""Generates `docs/METRICS.md` from the live `REGISTRY` (spec §8.2), so the document and the
running code can never disagree about what a metric means (CLAUDE.md's freshness-test
convention). `manage.py metrics_doc` writes the file; a test compares this render against the
committed bytes."""

from __future__ import annotations

from django.utils import translation
from django.utils.encoding import force_str

from apps.metrics.models import ScopeType
from apps.metrics.registry import REGISTRY, MetricDef

_MODULE_GROUP = {
    "adoption": "Adoption",
    "flow": "Flow",
    "state": "Flow",
    "quality": "Quality",
    "compliance": "Compliance",
}
_GROUP_ORDER = ["Adoption", "Flow", "Quality", "Compliance"]

_LEVEL_LABEL: dict[str, str] = {
    ScopeType.GLOBAL: "global",
    ScopeType.PROJECT: "project",
    ScopeType.REPO: "repo",
    ScopeType.PERSON: "person",
}


def _calculator_callable(metric_def: MetricDef):
    calculator = metric_def.calculator
    for attr in ("daily", "numerator", "period", "at_date"):
        callable_ = getattr(calculator, attr, None)
        if callable_ is not None:
            return callable_
    raise ValueError(f"Metric {metric_def.key!r} has a calculator with no recognised callable field.")


def _group_for(metric_def: MetricDef) -> str:
    module = _calculator_callable(metric_def).__module__
    module_name = module.rsplit(".", 1)[-1]
    return _MODULE_GROUP.get(module_name, module_name)


def _levels_cell(metric_def: MetricDef) -> str:
    return ", ".join(_LEVEL_LABEL[level] for level in ScopeType.values if level in metric_def.levels)


def _cohorts_cell(metric_def: MetricDef) -> str:
    return "all, ai, non_ai" if metric_def.supports_cohorts else "all only"


def render_metrics_doc() -> str:
    """The English Markdown document. Rendered under `translation.override("en")` so
    `gettext_lazy` titles/descriptions come out in English regardless of the active language
    (CLAUDE.md: generated documents are English even when the UI is Ukrainian)."""
    with translation.override("en"):
        by_group: dict[str, list[MetricDef]] = {}
        for metric_def in REGISTRY.values():
            by_group.setdefault(_group_for(metric_def), []).append(metric_def)

        lines = [
            "# Metrics",
            "",
            "Generated by `manage.py metrics_doc` from `apps/metrics/registry.py` — do not edit by "
            "hand, regenerate and commit instead.",
            "",
        ]

        groups = sorted(by_group, key=lambda name: _GROUP_ORDER.index(name) if name in _GROUP_ORDER else 99)
        for group in groups:
            metric_defs = sorted(by_group[group], key=lambda metric_def: metric_def.key)
            lines.append(f"## {group}")
            lines.append("")
            lines.append("| Key | Title | Unit | Kind | Direction | Levels | Cohorts | Formula |")
            lines.append("|---|---|---|---|---|---|---|---|")
            for metric_def in metric_defs:
                lines.append(
                    f"| `{metric_def.key}` | {force_str(metric_def.title)} | {metric_def.unit} | "
                    f"{metric_def.kind} | {metric_def.direction} | {_levels_cell(metric_def)} | "
                    f"{_cohorts_cell(metric_def)} | {metric_def.formula} |"
                )
            lines.append("")

        lines.append("## Definitions")
        lines.append("")
        for group in groups:
            metric_defs = sorted(by_group[group], key=lambda metric_def: metric_def.key)
            for metric_def in metric_defs:
                lines.append(f"### `{metric_def.key}`")
                lines.append("")
                lines.append(force_str(metric_def.description))
                lines.append("")
                if metric_def.params:
                    params = ", ".join(f"{key}={value}" for key, value in sorted(metric_def.params.items()))
                    lines.append(f"Params: {params}")
                    lines.append("")

        return "\n".join(lines).rstrip("\n") + "\n"
