# Generated by Django 5.2.17 on 2026-09-17 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=200, unique=True, verbose_name='login')),
                ('type', models.CharField(choices=[('org', 'Organization'), ('user', 'User')], max_length=10, verbose_name='type')),
                ('github_id', models.CharField(max_length=100, unique=True, verbose_name='GitHub node id')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('raw', models.JSONField(blank=True, null=True, verbose_name='raw payload')),
            ],
            options={
                'verbose_name': 'organization',
                'verbose_name_plural': 'organizations',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=200, verbose_name='display name')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('is_bot', models.BooleanField(default=False, verbose_name='is bot')),
                ('exclude_from_metrics', models.BooleanField(default=False, verbose_name='exclude from metrics')),
                ('team', models.CharField(blank=True, max_length=200, verbose_name='team')),
                ('role_hint', models.CharField(blank=True, choices=[('dev', 'Developer'), ('qa', 'QA'), ('design', 'Design'), ('other', 'Other')], max_length=20, verbose_name='role hint')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
            ],
            options={
                'verbose_name': 'person',
                'verbose_name_plural': 'people',
                'indexes': [models.Index(fields=['is_active', 'is_bot'], name='catalog_per_is_acti_496d94_idx')],
            },
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('full_name', models.CharField(max_length=400, unique=True, verbose_name='full name')),
                ('github_id', models.CharField(max_length=100, unique=True, verbose_name='GitHub node id')),
                ('default_branch', models.CharField(blank=True, max_length=200, verbose_name='default branch')),
                ('is_private', models.BooleanField(default=False, verbose_name='is private')),
                ('is_archived', models.BooleanField(default=False, verbose_name='is archived')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('sync_since', models.DateField(blank=True, null=True, verbose_name='sync since')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='last synced at')),
                ('sync_cursor', models.JSONField(blank=True, default=dict, verbose_name='sync cursor')),
                ('merge_strategy_hint', models.CharField(blank=True, max_length=50, verbose_name='merge strategy hint')),
                ('raw', models.JSONField(blank=True, null=True, verbose_name='raw payload')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repositories', to='connections.githubconnection', verbose_name='connection')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='catalog.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'repository',
                'verbose_name_plural': 'repositories',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('color', models.CharField(choices=[('series-1', 'series-1'), ('series-2', 'series-2'), ('series-3', 'series-3'), ('series-4', 'series-4'), ('series-5', 'series-5'), ('series-6', 'series-6'), ('series-7', 'series-7'), ('series-8', 'series-8')], default='series-1', max_length=20, verbose_name='color')),
                ('repositories', models.ManyToManyField(blank=True, related_name='projects', to='catalog.repository', verbose_name='repositories')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
            },
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('github_login', 'GitHub login'), ('git_email', 'Git email')], max_length=20, verbose_name='kind')),
                ('value', models.CharField(max_length=320, verbose_name='value')),
                ('github_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='GitHub node id')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True, verbose_name='first seen at')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identities', to='catalog.person', verbose_name='person')),
            ],
            options={
                'verbose_name': 'identity',
                'verbose_name_plural': 'identities',
                'indexes': [models.Index(fields=['person'], name='catalog_ide_person__9340bb_idx')],
                'constraints': [models.UniqueConstraint(fields=('kind', 'value'), name='uniq_identity_kind_value')],
            },
        ),
        migrations.AddIndex(
            model_name='repository',
            index=models.Index(fields=['is_active', 'last_synced_at'], name='catalog_rep_is_acti_f8fd04_idx'),
        ),
    ]
