# Generated by Django 5.2.17 on 2026-09-17 06:15

from django.db import migrations, models

from apps.catalog.setting_defs import SETTING_DEFS


def seed_defaults(apps, schema_editor):
    AppSetting = apps.get_model("catalog", "AppSetting")
    existing_keys = set(AppSetting.objects.values_list("key", flat=True))
    for setting_def in SETTING_DEFS:
        if setting_def.key in existing_keys:
            continue
        AppSetting.objects.create(
            key=setting_def.key,
            value_type=setting_def.value_type,
            value=setting_def.default,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='key')),
                ('value_type', models.CharField(max_length=10, verbose_name='value type')),
                ('value', models.JSONField(verbose_name='value')),
                ('description', models.CharField(blank=True, max_length=400, verbose_name='description')),
            ],
            options={
                'verbose_name': 'app setting',
                'verbose_name_plural': 'app settings',
                'permissions': [('manage_settings', 'Can manage settings')],
            },
        ),
        migrations.RunPython(seed_defaults, migrations.RunPython.noop),
    ]
