# Generated by Django 5.2.17 on 2026-09-20 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_bot_logins_ai_reviewers'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='ai_tooling_checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='AI tooling checked at'),
        ),
        migrations.AddField(
            model_name='repository',
            name='ai_tooling_paths',
            field=models.JSONField(blank=True, default=list, verbose_name='AI tooling paths'),
        ),
    ]
